<?php

$produtos = array(
    0 => array('nome' =>'NFT macaco1','preço' => '2000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_branco.png'),
    1 => array('nome' =>'NFT macaco2','preço' => '1000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_lazer.png'),
    2 => array('nome' =>'NFT macaco3','preço' => '1500,00 R$', 'descricao'=>'Nft macaco','imagem'=>'Eminem-NFT.webp'),
    3 => array('nome' =>'NFT macaco4','preço' => '2300,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_lazer.png'),
    4 => array('nome' =>'NFT macaco5','preço' => '1700,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_tralha.jpg'),
    5 => array('nome' =>'NFT macaco6','preço' => '2800,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_lutador.jpg'),
    6 => array('nome' =>'NFT macaco7','preço' => '3000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    7 => array('nome' =>'NFT macaco8','preço' => '3500,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_marinheiro.png'),
    8 => array('nome' =>'NFT macaco9','preço' => '3400,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macac_.png'),
    9 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    10 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    11 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    12 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    13 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    14 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    15 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    16 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    17 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    18 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    19 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    20 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    21 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    22 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    23 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    24 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    25 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    26 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    27 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    28 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
    29 => array('nome' =>'NFT macaco10','preço' => '4000,00 R$', 'descricao'=>'Nft macaco','imagem'=>'macaco_chapeu.png'),
   
);
?> 
